# Generated by Django 5.0.7 on 2024-08-22 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='author',
        ),
    ]
