# Generated by Django 5.0.7 on 2024-07-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_qna'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
