# Generated by Django 5.0.7 on 2024-08-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_userfollow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
