# Generated by Django 5.0.7 on 2024-08-22 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_remove_userprofile_bio_remove_userprofile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userfollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='userprofile.userprofile')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to='userprofile.userprofile')),
            ],
        ),
    ]
